hub_recipes_yummly_client_homepage:
    pattern:  /recipes/{name}
    defaults: { _controller: HubRecipesYummlyClientBundle:Default:index }

results:
    pattern:  /results
    defaults: { _controller: HubRecipesYummlyClientBundle:Default:searchResults }

by_Cuisine:
    pattern:  /Cuisine/{cuisine}/{start}
    defaults: { _controller: HubRecipesYummlyClientBundle:Default:searchByCuisine }

loadMoreItems:
    pattern:  /loadMoreItems
    defaults: { _controller: HubRecipesYummlyClientBundle:Default:loadMoreItems }

fill:
    pattern:  /fill
    defaults: { _controller: HubRecipesYummlyClientBundle:Default:fillIngredients }