hub_recipes_yummly_client_homepage:
    pattern:  /recipes/{name}
    defaults: { _controller: HubRecipesYummlyClientBundle:Default:index }

results:
    pattern:  /results
    defaults: { _controller: HubRecipesYummlyClientBundle:Default:searchResults }

by_Cuisine:
    pattern:  /Cuisine/{cuisine}/{start}
    defaults: { _controller: HubRecipesYummlyClientBundle:Default:searchByCuisine }

loadMoreCuisine:
    pattern:  /loadMoreCuisine
    defaults: { _controller: HubRecipesYummlyClientBundle:Default:loadMoreCuisine }