hub_recipes_yummly_client_homepage:
    pattern:  /recipes/{name}
    defaults: { _controller: HubRecipesYummlyClientBundle:Default:index }

results:
    pattern:  /results
    defaults: { _controller: HubRecipesYummlyClientBundle:Default:searchResults }

by_Cuisine:
    pattern:  /Cuisine/{cuisine}/{start}
    defaults: { _controller: HubRecipesYummlyClientBundle:Default:searchByCuisine }

by_Emotion:
    pattern:  /Emotion/{emotion}
    defaults: { _controller: HubRecipesYummlyClientBundle:Default:getRecipesByEmotion }

by_Emotion_load_more:
    pattern:  /Emotions/{emotion}
    defaults: { _controller: HubRecipesYummlyClientBundle:Default:loadMoreByEmotion }

loadMoreItems:
    pattern:  /loadMoreItems
    defaults: { _controller: HubRecipesYummlyClientBundle:Default:loadMoreItems }

fill:
    pattern:  /fill
    defaults: { _controller: HubRecipesYummlyClientBundle:Default:fillIngredients }