parameters:
    hub_recipes_yummly_client.http.class: GuzzleHttp\Client
    hub_recipes_yummly_client.http.base_url: http://yumly.com/json/


    hub_recipes_yummly_client.search_service.class: HubRecipes\YummlyClientBundle\Service\SearchService

services:
    hub_recipes_yummly_client.http:
        class: %hub_recipes_yummly_client.http.class%
        arguments:
          - { base_url: %hub_recipes_yummly_client.http.base_url% }

    hub_recipes_yummly_client.search_service:
        class: %hub_recipes_yummly_client.search_service.http%
        arguments:
          - @hub_recipes_yummly_client.http
