parameters:
#    hub_recipes_yummly_client.example.class: HubRecipes\YummlyClientBundle\Example

services:
#    hub_recipes_yummly_client.example:
#        class: %hub_recipes_yummly_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
