parameters:
#    hubrecipes_users.example.class: Hubrecipes\UsersBundle\Example

services:
#    hubrecipes_users.example:
#        class: %hubrecipes_users.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
