hub_recipes_front_end_homepage:
    pattern:  /
    defaults: { _controller: HubRecipesFrontEndBundle:Default:index }

single_recipe:
    pattern: /recipe/{id}
    defaults: { _controller: HubRecipesFrontEndBundle:Default:recipe }

full_recipe:
    pattern: /recipe/full/{id}
    defaults: { _controller: HubRecipesFrontEndBundle:Default:fullRecipe }

autoComplete:
    pattern: /autoComplete
    defaults: { _controller: HubRecipesFrontEndBundle:Default:getIngredients }

exists:
    pattern: /exists
    defaults: { _controller: HubRecipesFrontEndBundle:Default:exists }