hub_recipes_front_end_homepage:
    pattern:  /
    defaults: { _controller: HubRecipesFrontEndBundle:Default:index }

loadMoreHomePage:
    pattern:  /loadMoreHomePage
    defaults: { _controller: HubRecipesFrontEndBundle:Default:loadMoreHomePage }

single_recipe:
    pattern: /recipe/{id}
    defaults: { _controller: HubRecipesFrontEndBundle:Default:recipe }

favourites:
    pattern: /favourites
    defaults: { _controller: HubRecipesFrontEndBundle:Default:favourites }

full_recipe:
    pattern: /recipe/full/{id}
    defaults: { _controller: HubRecipesFrontEndBundle:Default:fullRecipe }

autoComplete:
    pattern: /autoComplete
    defaults: { _controller: HubRecipesFrontEndBundle:Default:getIngredients }

exists:
    pattern: /exists
    defaults: { _controller: HubRecipesFrontEndBundle:Default:exists }